"""
Converts the OFFICIAL LOINC release (Loinc.csv, from a free download at
https://loinc.org — click "Download LOINC Table File", free registration
required) into this app's data/loinc_subset.csv format, filtered down to a
manageable, relevant subset for a medical report interpreter.

Why this script exists: earlier attempts to grow loinc_subset.csv by asking
an LLM to recall more codes from memory produced ~55 fabricated entries
(codes generated by incrementing a digit off a real nearby code rather than
being genuine, distinct LOINC identifiers) before being caught and removed.
This script is the honest alternative — it only ever copies codes that exist
in the real, authoritative LOINC table, so growing test coverage this way
carries zero fabrication risk.

Usage:
    1. Download Loinc.csv from https://loinc.org (Download LOINC Table File)
    2. Unzip it — you want LoincTable/Loinc.csv from the release
    3. cd backend
    4. python scripts/import_official_loinc.py /path/to/Loinc.csv
"""
import csv
import re
import sys
from pathlib import Path

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "data" / "loinc_subset.csv"

# LOINC's own CLASS field values that map to categories used in this app.
CLASS_TO_CATEGORY = {
    "HEM/BC": "CBC", "CHEM": "Chemistry", "COAG": "Coagulation",
    "DRUG/TOX": "Toxicology", "SERO": "Immunology", "MICRO": "Infectious",
    "UA": "Urine", "CHAL": "Endocrine",
}

# Only include entries with a genuine COMMON_TEST_RANK. LOINC uses rank 0 to
# mean "not ranked" (i.e. NOT "most common") — a prior version of this script
# treated 0 as passing the "<= MAX_RANK" check, which let through ~36,000
# unranked, often extremely obscure entries. Fixed: rank must be > 0 AND
# <= MAX_RANK. Calibrated against known common tests (Hemoglobin=17,
# Creatinine=4, Glucose=6, ALT=24, HbA1c=88) — 1000 extends into moderately
# specialized tests (urine microscopy sub-findings, drug metabolite panels,
# some genetic markers); still all real, but noticeably less universally
# relevant per test than the 1-400 core range.
MAX_RANK = 1000

# RELATEDNAMES2 mixes genuinely useful synonyms with generic method/unit/
# category boilerplate that appears on nearly every row regardless of the
# specific test. Filtering this noise out keeps synonym lists meaningful for
# fuzzy matching instead of diluting them with words like "Plasma" or "Quant".
SYNONYM_STOPWORDS = {
    "chemistry", "hematology", "hemostasis", "coagulation", "microbiology",
    "serology", "endocrinology", "endocrine", "nephrology", "hepatology",
    "cardiology", "toxicology", "immunology", "renal", "kidney", "liver",
    "blood", "serum", "plasma", "urine", "pl", "plsm", "serp", "serpl",
    "serplas", "ser/plas", "bld", "point in time", "random", "timed",
    "24 hour", "quantitative", "qualitative", "quant", "quan", "qnt", "ql",
    "ordinal", "nominal", "mass concentration", "mass fraction",
    "substance concentration", "arbitrary concentration", "level",
    "measurement", "moles/volume", "catalytic concentration", "titer",
    "presence", "identity", "number", "count", "ratio", "and", "or",
    "hematology/cell counts", "limitedUseLabOrders".lower(), "auto",
    "automated detection", "manual", "manl", "elec", "elect", "electr",
    "abs", "absolute", "absolutes", "cnt", "ct", "count/volume", "lm",
    "micro", "micros", "microscopic", "pr", "number fraction", "prctl",
    "arvrat", "leuc", "leuk", "leukocyte", "lkcs",
}


def _is_low_quality_token(token: str) -> bool:
    """Catches tokens that slip past the exact-match stopword list: all-caps
    multi-word metadata labels (e.g. "HEMATOLOGY/CELL COUNTS"), and very
    short cryptic codes that aren't useful as human-facing synonyms."""
    if token.isupper() and (" " in token or "/" in token) and len(token) > 6:
        return True
    if len(token) <= 3 and not token.isalpha():
        return True
    return False


def _clean_synonyms(raw: str, exclude: str) -> str:
    parts = [p.strip() for p in raw.split(";") if p.strip()]
    seen: list[str] = []
    exclude_lower = exclude.lower()
    for part in parts:
        lowered = part.lower()
        if lowered in SYNONYM_STOPWORDS or lowered == exclude_lower:
            continue
        if len(part) < 2:
            continue
        if _is_low_quality_token(part):
            continue
        if part not in seen:
            seen.append(part)
    return ";".join(seen[:8])  # cap to keep rows readable


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: python import_official_loinc.py /path/to/Loinc.csv")
        sys.exit(1)

    source_path = Path(sys.argv[1])
    if not source_path.exists():
        print(f"File not found: {source_path}")
        sys.exit(1)

    existing_codes: set[str] = set()
    existing_names: set[str] = set()  # names already covered (curated or prior import)
    existing_rows: list[dict] = []
    if OUTPUT_PATH.exists():
        with open(OUTPUT_PATH, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                existing_codes.add(row["loinc_code"])
                existing_names.add(row["common_name"].strip().lower())
                existing_rows.append(row)

    # Collect ALL candidate new rows first (with their rank), so that when the
    # official file has multiple LOINC codes sharing the same COMPONENT name
    # (different specimen types/methods — e.g. Hemoglobin has 6+ codes), only
    # the single best-ranked (most common) one is kept. Without this, matching
    # against report text becomes fragile: whichever variant happened to
    # appear earlier in the source file would "win" arbitrarily, not
    # necessarily the clinically default one.
    candidates: dict[str, tuple[int, dict]] = {}  # name -> (rank, row_dict)

    with open(source_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("STATUS", "").strip().upper() != "ACTIVE":
                continue  # skip deprecated/discouraged/trial codes

            code = row.get("LOINC_NUM", "").strip()
            if not code or code in existing_codes:
                continue

            klass = row.get("CLASS", "").strip()
            category = CLASS_TO_CATEGORY.get(klass)
            if not category:
                continue

            try:
                rank = int(row.get("COMMON_TEST_RANK", "") or 0)
            except ValueError:
                rank = 0
            if rank <= 0 or rank > MAX_RANK:
                continue  # 0 = unranked (not "most common"); excluded, not included

            # COMPONENT is the cleanest, most patient-readable field LOINC provides
            # (e.g. "Glomerular filtration rate" vs SHORTNAME's "GFRSerPlBld
            # MDRD-ArVRat"). SHORTNAME is kept as a synonym instead, since report
            # text sometimes uses that terser form.
            component = (row.get("COMPONENT") or "").strip()
            shortname = (row.get("SHORTNAME") or "").strip()
            name = component or shortname
            if not name:
                continue
            name = name.replace(".", " ").replace("  ", " ").strip()
            name_key = name.lower()

            if name_key in existing_names:
                continue  # a curated or already-imported entry already covers this test name

            if name_key in candidates and candidates[name_key][0] <= rank:
                continue  # already have a better (lower-rank = more common) candidate for this name

            synonyms_list = []
            if shortname and shortname.lower() != name.lower():
                synonyms_list.append(shortname)
            extra = _clean_synonyms(row.get("RELATEDNAMES2", ""), name)
            if extra:
                synonyms_list.extend(extra.split(";"))
            synonyms = ";".join(dict.fromkeys(synonyms_list))  # dedupe, preserve order

            candidates[name_key] = (rank, {
                "loinc_code": code,
                "common_name": name,
                "synonyms": synonyms,
                "category": category,
            })

    new_rows = [row for _, row in candidates.values()]

    all_rows = existing_rows + new_rows
    fieldnames = ["loinc_code", "common_name", "synonyms", "category"]
    with open(OUTPUT_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"Added {len(new_rows)} new tests from the official LOINC table.")
    print(f"Total tests now: {len(all_rows)}")


if __name__ == "__main__":
    main()

